/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    events: Event;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    roder: Roder;
    sarnafil: Sarnafil;
    'peralatan-pendukung': PeralatanPendukung;
  };
  globalsSelect: {
    roder: RoderSelect<false> | RoderSelect<true>;
    sarnafil: SarnafilSelect<false> | SarnafilSelect<true>;
    'peralatan-pendukung': PeralatanPendukungSelect<false> | PeralatanPendukungSelect<true>;
  };
  locale: null;
  widgets: {
    'at-a-glance': AtAGlanceWidget;
    'events-by-category': EventsByCategoryWidget;
    'category-pages': CategoryPagesWidget;
    'recent-activity': RecentActivityWidget;
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * The three cards in Products on the home page, and the entries in the navbar's Products menu. Each card links to a category page — edit the page itself under Category Pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * The product name as it reads on the card.
   */
  title: string;
  /**
   * One or two sentences under the title.
   */
  description?: string | null;
  /**
   * Which category page this card opens — and which page's hero image it borrows. One card per category.
   */
  category_key: 'roder' | 'sarnafil' | 'peralatan-pendukung';
  /**
   * Lowest number shows first.
   */
  display_order?: number | null;
  /**
   * Read-only. This is the hero image from the category page above — change it there and this card follows.
   */
  hero_image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Every image, video and PDF used on the site. Upload here once and pick the file from a product, event or category page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * A short description of what is in the image, for screen readers and search engines. Describe the subject, not the file — "Tenda Sarnafil di halaman kantor", not "foto 1".
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Past events, shown on the home page and on /events. Only published events appear on the site — a draft stays private until you hit Publish.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * The heading on the card, e.g. "Gathering Telkom Indonesia".
   */
  name: string;
  /**
   * One photo from the event. Landscape crops best on the card.
   */
  image?: (number | null) | Media;
  /**
   * Shown as a chip on the card. Leave empty to show no chip.
   */
  event_category?: ('korporat' | 'pemerintahan' | 'keagamaan' | 'festival' | 'bazaar' | 'wedding' | 'komunitas') | null;
  /**
   * Where it was held, e.g. "Jakarta Convention Center".
   */
  location?: string | null;
  /**
   * How long it ran, e.g. "3 hari".
   */
  duration?: string | null;
  /**
   * Lowest number first. Events sharing a number fall back to when they were added.
   */
  display_order?: number | null;
  /**
   * Not used by the site yet. Ticking it changes nothing on the page — use Order to control what shows first.
   */
  is_featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * People who can sign in and edit this site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown instead of the email address where there is room for it.
   */
  name?: string | null;
  /**
   * Admins edit all of the site content. The superadmin does that and manages this list of users — there can only be one.
   */
  role: 'superadmin' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category_key?: T;
  display_order?: T;
  hero_image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  event_category?: T;
  location?: T;
  duration?: T;
  display_order?: T;
  is_featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Everything on /products/roder, top to bottom.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roder".
 */
export interface Roder {
  id: number;
  /**
   * The big heading at the top of the page.
   */
  title: string;
  /**
   * The paragraph under the heading.
   */
  description?: string | null;
  /**
   * The banner at the top of the page. This is also the image on the product card on the home page.
   */
  hero_image?: (number | null) | Media;
  use_cases: {
    /**
     * The heading printed above this section on the page.
     */
    group_name: string;
    items?:
      | {
          name: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  size_variants: {
    /**
     * The heading printed above this section on the page.
     */
    group_name: string;
    items?:
      | {
          /**
           * e.g. "10 x 20 m".
           */
          name: string;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  jenis_roder: {
    /**
     * The heading printed above this section on the page.
     */
    group_name: string;
    items?:
      | {
          name: string;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  pilihan_dinding: {
    /**
     * The heading printed above this section on the page.
     */
    group_name: string;
    items?:
      | {
          name: string;
          description?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  specifications: {
    /**
     * The heading printed above this section on the page.
     */
    group_name: string;
    items?:
      | {
          /**
           * Left column, e.g. "Material atap".
           */
          label: string;
          /**
           * Right column.
           */
          value?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  yang_anda_dapatkan: {
    /**
     * The heading printed above this section on the page.
     */
    group_name: string;
    items?:
      | {
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  flooring_modul: {
    /**
     * The heading printed above this section on the page.
     */
    group_name: string;
    /**
     * Explains what flooring modul is, above the photos.
     */
    description?: string | null;
    items?:
      | {
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  pertanyaan_umum: {
    /**
     * The heading printed above this section on the page.
     */
    group_name: string;
    items?:
      | {
          question: string;
          answer?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Everything on /products/sarnafil, top to bottom.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sarnafil".
 */
export interface Sarnafil {
  id: number;
  /**
   * The big heading at the top of the page.
   */
  title: string;
  /**
   * The paragraph under the heading.
   */
  description?: string | null;
  /**
   * The banner at the top of the page. This is also the image on the product card on the home page.
   */
  hero_image?: (number | null) | Media;
  use_cases: {
    /**
     * The heading printed above this section on the page.
     */
    group_name: string;
    items?:
      | {
          name: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  size_variants: {
    /**
     * The heading printed above this section on the page.
     */
    group_name: string;
    items?:
      | {
          /**
           * e.g. "10 x 20 m".
           */
          name: string;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  specifications: {
    /**
     * The heading printed above this section on the page.
     */
    group_name: string;
    items?:
      | {
          /**
           * Left column, e.g. "Material atap".
           */
          label: string;
          /**
           * Right column.
           */
          value?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  yang_anda_dapatkan: {
    /**
     * The heading printed above this section on the page.
     */
    group_name: string;
    items?:
      | {
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  flooring_modul: {
    /**
     * The heading printed above this section on the page.
     */
    group_name: string;
    /**
     * Explains what flooring modul is, above the photos.
     */
    description?: string | null;
    items?:
      | {
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  pertanyaan_umum: {
    /**
     * The heading printed above this section on the page.
     */
    group_name: string;
    items?:
      | {
          question: string;
          answer?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Everything on /products/peralatan-pendukung, top to bottom.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "peralatan-pendukung".
 */
export interface PeralatanPendukung {
  id: number;
  /**
   * The big heading at the top of the page.
   */
  title: string;
  /**
   * The paragraph under the heading.
   */
  description?: string | null;
  /**
   * The banner at the top of the page. This is also the image on the product card on the home page.
   */
  hero_image?: (number | null) | Media;
  /**
   * One group per kind of equipment, e.g. Dekorasi & Ruangan, Kursi & Meja. Each group prints its own heading on the page, so there is no heading above them.
   */
  equipment_groups?:
    | {
        /**
         * The heading printed above this group on the page.
         */
        group_name: string;
        /**
         * A photo and a name for each piece of equipment in this group.
         */
        items?:
          | {
              name: string;
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roder_select".
 */
export interface RoderSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  hero_image?: T;
  use_cases?:
    | T
    | {
        group_name?: T;
        items?:
          | T
          | {
              name?: T;
              description?: T;
              id?: T;
            };
      };
  size_variants?:
    | T
    | {
        group_name?: T;
        items?:
          | T
          | {
              name?: T;
              image?: T;
              id?: T;
            };
      };
  jenis_roder?:
    | T
    | {
        group_name?: T;
        items?:
          | T
          | {
              name?: T;
              image?: T;
              id?: T;
            };
      };
  pilihan_dinding?:
    | T
    | {
        group_name?: T;
        items?:
          | T
          | {
              name?: T;
              description?: T;
              image?: T;
              id?: T;
            };
      };
  specifications?:
    | T
    | {
        group_name?: T;
        items?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  yang_anda_dapatkan?:
    | T
    | {
        group_name?: T;
        items?:
          | T
          | {
              description?: T;
              id?: T;
            };
      };
  flooring_modul?:
    | T
    | {
        group_name?: T;
        description?: T;
        items?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  pertanyaan_umum?:
    | T
    | {
        group_name?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sarnafil_select".
 */
export interface SarnafilSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  hero_image?: T;
  use_cases?:
    | T
    | {
        group_name?: T;
        items?:
          | T
          | {
              name?: T;
              description?: T;
              id?: T;
            };
      };
  size_variants?:
    | T
    | {
        group_name?: T;
        items?:
          | T
          | {
              name?: T;
              image?: T;
              id?: T;
            };
      };
  specifications?:
    | T
    | {
        group_name?: T;
        items?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  yang_anda_dapatkan?:
    | T
    | {
        group_name?: T;
        items?:
          | T
          | {
              description?: T;
              id?: T;
            };
      };
  flooring_modul?:
    | T
    | {
        group_name?: T;
        description?: T;
        items?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  pertanyaan_umum?:
    | T
    | {
        group_name?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "peralatan-pendukung_select".
 */
export interface PeralatanPendukungSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  hero_image?: T;
  equipment_groups?:
    | T
    | {
        group_name?: T;
        items?:
          | T
          | {
              name?: T;
              image?: T;
              id?: T;
            };
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "at-a-glance_widget".
 */
export interface AtAGlanceWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-by-category_widget".
 */
export interface EventsByCategoryWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "category-pages_widget".
 */
export interface CategoryPagesWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recent-activity_widget".
 */
export interface RecentActivityWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}